name: build
on:
  push:
    branches:
    - master
    - v*
    tags:
    - v*
  pull_request:
jobs:
  build:
    name: Build binaries
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Build binaries
    - name: Run ci
      run: make ci

    - uses: codecov/codecov-action@v4
      with:
        files: ./coverage.out
        flags: unittests
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries_artifact
        path: ./bin/*

  build_push_image:
    name: Build and push image
    runs-on: self-hosted
    needs: build
    if: ${{ startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/') }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: binaries_artifact
        path: ./bin/

    - name: Add executable permission
      run: |
        chmod +x ./bin/*

    - name: Copy bin folder to package
      run: |
        cp -r ./bin ./package/

    # For multi-platform support
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Declare branch
      run: |
        echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_ENV"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV

    # longhornio/longhorn-manager image
    - name: docker-publish
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        platforms: linux/amd64,linux/arm64
        tags: mdsina/longhorn-manager:${{ env.branch }}-head , mdsina/longhorn-manager:${{ env.branch }}-${{ env.SHORT_SHA }}
        file: package/Dockerfile
        sbom: true

    - name: docker-publish-with-tag
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: docker/build-push-action@v5
      with:
        context: ./
        push: true
        platforms: linux/amd64,linux/arm64
        tags: mdsina/longhorn-manager:${{ github.ref_name }}
        file: package/Dockerfile
        sbom: true
